import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home({ data }) {
  console.log("HOME component", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Bird Squawk App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a> Welcome to Bird Squawk App!</a>
        </h1>
        <p>
          Fetch data -> name: {data?.name}, age: {data?.age}
        </p>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://api.agify.io/?name=Birdy");
  const data = await res.json();

  console.log("Function start on server --->", res);

  return { props: { data } };
}

export default Home;
